# 1) what is missing data

- missing data means some values are not available

In [35]:
import pandas as pd 
import numpy as np

In [36]:
data = {
    "name": ["jhon","don","fone"],
    "age": [28,np.nan,25]
}

In [37]:
data

{'name': ['jhon', 'don', 'fone'], 'age': [28, nan, 25]}

In [38]:
df = pd.DataFrame(data)
df

   name   age
0  jhon  28.0
1   don   NaN
2  fone  25.0

- here NaN IS Missing Value

In [39]:
df.dtypes

name     object
age     float64
dtype: object

# 2. Types of Missing Values in Pandas

In [40]:
np.nan

nan

- 1) used for numeric data np.nan

- 2) Used for Date and Time columns. pd.NaT

In [41]:
pd.Series([
    pd.Timestamp("2025-01-01"),
    pd.NaT
])

0   2025-01-01
1          NaT
dtype: datetime64[ns]

- 3) used for New universal missing value. pd.NA
  4) Why use pd.NA?

Because it preserves datatype.

In [42]:
pd.Series([1,2,None],dtype="Int64")

0       1
1       2
2    <NA>
dtype: Int64

# 3. Detect Missing Values

- isna()
- Returns True where value is missing.

In [43]:
s = pd.Series([1,np.nan])
s.isna()

0    False
1     True
dtype: bool

In [44]:
s = pd.Series([1,np.nan])
s.notna()
# it is opposite of isna()

0     True
1    False
dtype: bool

# 4. Why == np.nan Doesn't Work?

In [45]:
np.nan == np.nan

False

In [46]:
pd.NaT == pd.NaT

False

In [47]:
# this is not the correct way to compair

In [48]:
# the correct way 
df["age"].isna()

0    False
1     True
2    False
Name: age, dtype: bool

# 5. Arithmetic with Missing Values

In [49]:
pd.NA + 1

In [50]:
1 + pd.NA

- means if series has any unknow or  
- missing data on that particular we can not perform the artimc operations

# 6. Boolean Logic with NA

In [51]:
True | pd.NA

True

- True OR anything = True

In [52]:
False | pd.NA

- Because result depends on unknown value

In [53]:
False & pd.NA

False

- False AND anything = False

# 7. Why bool(pd.NA) gives Error?

In [54]:
bool(pd.NA)

TypeError: boolean value of NA is ambiguous

- Because pandas doesn't know whether NA is True or False.

# 8. Convert Old NaN Types

In [57]:
df.convert_dtypes()

   name   age
0  jhon    28
1   don  <NA>
2  fone    25

In [58]:
df.dtypes

name     object
age     float64
dtype: object

# 9. Insert Missing Values

In [59]:
df

   name   age
0  jhon  28.0
1   don   NaN
2  fone  25.0

In [60]:
df.loc[0] = None

In [61]:
df

   name   age
0  None   NaN
1   don   NaN
2  fone  25.0

# 10. Calculations with Missing Data

In [62]:
pd.Series([np.nan]).sum()

np.float64(0.0)

In [63]:
pd.Series([np.nan]).prod()

np.float64(1.0)

- Why does it return 1.0 instead of NaN?

- By default:

- skipna=True

- Pandas ignores missing values.

- After ignoring NaN, there are no values left.

- The product of an empty set is mathematically defined as: 1

# 11. Cumulative Functions

In [65]:
df

   name   age
0  None   NaN
1   don   NaN
2  fone  25.0

# 12. Removing Missing Data

In [69]:
df

   name   age
0  None   NaN
1   don   NaN
2  fone  25.0

In [70]:
df.dropna()

   name   age
2  fone  25.0

In [71]:
df

   name   age
0  None   NaN
1   don   NaN
2  fone  25.0

In [73]:
df.dropna(axis=0)

   name   age
2  fone  25.0

In [77]:
df

   name   age
0  None   NaN
1   don   NaN
2  fone  25.0

In [84]:
df.dropna(axis=1) # v = 1 column  h= 0 row

Empty DataFrame
Columns: []
Index: [0, 1, 2]

In [85]:
df

   name   age
0  None   NaN
1   don   NaN
2  fone  25.0

In [86]:
df.dtypes

name     object
age     float64
dtype: object

In [87]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3 entries, 0 to 2
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   name    2 non-null      object
 1   age     1 non-null      float64
dtypes: float64(1), object(1)
memory usage: 180.0+ bytes

# 13. Fill Missing Values

In [89]:
df.fillna(1)

   name   age
0     1   1.0
1   don   1.0
2  fone  25.0

In [91]:
df

   name   age
0  None   NaN
1   don   NaN
2  fone  25.0

In [95]:
df = pd.DataFrame({
    'A': [1, np.nan, np.nan, 4],
    'B': ['x', np.nan, 'z', np.nan]
})

print(df)

     A    B
0  1.0    x
1  NaN  NaN
2  NaN    z
3  4.0  NaN

In [97]:
df.ffill()  # forward filling

     A  B
0  1.0  x
1  1.0  x
2  1.0  z
3  4.0  z

In [98]:
df

     A    B
0  1.0    x
1  NaN  NaN
2  NaN    z
3  4.0  NaN

In [99]:
df.interpolate()

/var/folders/vc/w3_sxb6x2g16jqk905nfn07h0000gn/T/ipykernel_46987/4002874584.py:1: FutureWarning: DataFrame.interpolate with object dtype is deprecated and will raise in a future version. Call obj.infer_objects(copy=False) before interpolating instead.
  df.interpolate()

     A    B
0  1.0    x
1  2.0  NaN
2  3.0    z
3  4.0  NaN

In [100]:
df

     A    B
0  1.0    x
1  NaN  NaN
2  NaN    z
3  4.0  NaN

In [103]:
df.replace('x',np.nan)

     A    B
0  1.0  NaN
1  NaN  NaN
2  NaN    z
3  4.0  NaN