# selecting a column

In [1]:
import numpy as np 
import pandas as pd

In [5]:
data = {
    'name':['jhon','roy','dome'],
    'age':[12,18,20]
}

In [6]:
data

{'name': ['jhon', 'roy', 'dome'], 'age': [12, 18, 20]}

In [7]:
df = pd.DataFrame(data)

In [8]:
df

   name  age
0  jhon   12
1   roy   18
2  dome   20

In [9]:
df['name']

0    jhon
1     roy
2    dome
Name: name, dtype: object

- adding new column

# Adding a columns

In [12]:
df['avgage'] = df['age'].mean()

In [13]:
df

   name  age     avgage
0  jhon   12  16.666667
1   roy   18  16.666667
2  dome   20  16.666667

# 3. Deleting Columns

In [15]:
del df['avgage']

In [16]:
df

   name  age
0  jhon   12
1   roy   18
2  dome   20

- del Removes column permanently.

- Deletes and returns column

In [17]:
df

   name  age
0  jhon   12
1   roy   18
2  dome   20

In [24]:
df['avgage'] = df['age'].mean()

In [25]:
df

   name  age     avgage
0  jhon   12  16.666667
1   roy   18  16.666667
2  dome   20  16.666667

In [26]:
df.pop('avgage')

0    16.666667
1    16.666667
2    16.666667
Name: avgage, dtype: float64

In [27]:
df

   name  age
0  jhon   12
1   roy   18
2  dome   20

# 4. Assigning Scalar Value

In [28]:
df

   name  age
0  jhon   12
1   roy   18
2  dome   20

In [29]:
df["foo"] = "bar"

In [30]:
df

   name  age  foo
0  jhon   12  bar
1   roy   18  bar
2  dome   20  bar

# 5. Assigning Smaller Series

In [32]:
df["one_trunc"] = df["foo"][:2]

In [33]:
df

   name  age  foo one_trunc
0  jhon   12  bar       bar
1   roy   18  bar       bar
2  dome   20  bar       NaN

# 6. Inserting Column at Specific Position

In [37]:
df.insert(1,"test",df["one_trunc"])

In [38]:
df

   name test  bar  age  foo one_trunc
0  jhon  bar  bar   12  bar       bar
1   roy  bar  bar   18  bar       bar
2  dome  NaN  NaN   20  bar       NaN

In [40]:
# insert(location,column_name,calues)
# at which position we want to add new column

# 7. assign() Method

- df.assign(...)
- example 
- iris.assign(
    sepal_ratio=
    iris["SepalWidth"] /
    iris["SepalLength"]
)
- Very important for chaining operations.
- returns a copy.

- Original dataframe remains unchanged.

# 8. Using Lambda in assign()

In [41]:
df

   name test  bar  age  foo one_trunc
0  jhon  bar  bar   12  bar       bar
1   roy  bar  bar   18  bar       bar
2  dome  NaN  NaN   20  bar       NaN

In [42]:
df['name'] = df['name'].apply(lambda x: x.upper())

In [43]:
df

   name test  bar  age  foo one_trunc
0  JHON  bar  bar   12  bar       bar
1   ROY  bar  bar   18  bar       bar
2  DOME  NaN  NaN   20  bar       NaN

In [44]:
df['adult'] = df['age'].apply(lambda x: 'Yes' if x >= 18 else 'No')

In [45]:
df

   name test  bar  age  foo one_trunc adult
0  JHON  bar  bar   12  bar       bar    No
1   ROY  bar  bar   18  bar       bar   Yes
2  DOME  NaN  NaN   20  bar       NaN   Yes

# 9. Multiple Column Creation

In [46]:
df = df.assign(
    age_plus_10=lambda x: x['age'] + 10,
    adult=lambda x: x['age'] >= 18,
    name_upper=lambda x: x['name'].str.upper()
)

In [47]:
df

   name test  bar  age  foo one_trunc  adult  age_plus_10 name_upper
0  JHON  bar  bar   12  bar       bar  False           22       JHON
1   ROY  bar  bar   18  bar       bar   True           28        ROY
2  DOME  NaN  NaN   20  bar       NaN   True           30       DOME

# 10. Indexing and Selection

| Operation         | Syntax          | Result    |
| ----------------- | --------------- | --------- |
| Select column     | `df["A"]`       | Series    |
| Row by label      | `df.loc["a"]`   | Series    |
| Row by position   | `df.iloc[0]`    | Series    |
| Slice rows        | `df[1:4]`       | DataFrame |
| Boolean selection | `df[df["A"]>5]` | DataFrame |

loc  → labels
iloc → integer positions