# What is GroupBy?

Data
 ↓
Split into groups
 ↓
Apply some operation
 ↓
Combine results

In [1]:
import pandas as pd

df = pd.DataFrame({
    "Employee": ["Sachin","Rahul","Amit","Neha","Priya",
                 "Karan","Rohit","Pooja","Ankit","Simran"],

    "Department": ["IT","HR","IT","Finance","HR",
                   "Finance","IT","HR","Finance","IT"],

    "City": ["Indore","Delhi","Indore","Mumbai","Delhi",
             "Mumbai","Pune","Delhi","Mumbai","Pune"],

    "Salary": [50000,40000,60000,55000,45000,
               70000,65000,48000,72000,62000],

    "Experience": [2,1,4,3,2,6,5,2,7,4]
})

print(df)

  Employee Department    City  Salary  Experience
0   Sachin         IT  Indore   50000           2
1    Rahul         HR   Delhi   40000           1
2     Amit         IT  Indore   60000           4
3     Neha    Finance  Mumbai   55000           3
4    Priya         HR   Delhi   45000           2
5    Karan    Finance  Mumbai   70000           6
6    Rohit         IT    Pune   65000           5
7    Pooja         HR   Delhi   48000           2
8    Ankit    Finance  Mumbai   72000           7
9   Simran         IT    Pune   62000           4

In [2]:
df

  Employee Department    City  Salary  Experience
0   Sachin         IT  Indore   50000           2
1    Rahul         HR   Delhi   40000           1
2     Amit         IT  Indore   60000           4
3     Neha    Finance  Mumbai   55000           3
4    Priya         HR   Delhi   45000           2
5    Karan    Finance  Mumbai   70000           6
6    Rohit         IT    Pune   65000           5
7    Pooja         HR   Delhi   48000           2
8    Ankit    Finance  Mumbai   72000           7
9   Simran         IT    Pune   62000           4

In [4]:
df.groupby("Department").sum(numeric_only=True)

            Salary  Experience
Department
Finance     197000          16
HR          133000           5
IT          237000          15

In [7]:
df.groupby("Department")["Salary"].mean()

Department
Finance    65666.666667
HR         44333.333333
IT         59250.000000
Name: Salary, dtype: float64

In [8]:
df.groupby("Department")["Salary"].max()

Department
Finance    72000
HR         48000
IT         65000
Name: Salary, dtype: int64

In [9]:
df.groupby("Department")['Employee'].count()

Department
Finance    3
HR         3
IT         4
Name: Employee, dtype: int64

In [11]:
df.groupby('Department')['Salary'].transform('mean')

0    59250.000000
1    44333.333333
2    59250.000000
3    65666.666667
4    44333.333333
5    65666.666667
6    59250.000000
7    44333.333333
8    65666.666667
9    59250.000000
Name: Salary, dtype: float64

In [16]:
df

  Employee Department    City  Salary  Experience
0   Sachin         IT  Indore   50000           2
1    Rahul         HR   Delhi   40000           1
2     Amit         IT  Indore   60000           4
3     Neha    Finance  Mumbai   55000           3
4    Priya         HR   Delhi   45000           2
5    Karan    Finance  Mumbai   70000           6
6    Rohit         IT    Pune   65000           5
7    Pooja         HR   Delhi   48000           2
8    Ankit    Finance  Mumbai   72000           7
9   Simran         IT    Pune   62000           4

In [20]:
df.groupby(level=0)

In [21]:
df.groupby("Department").filter(
    lambda x: x["Salary"].mean() > 50000
)

  Employee Department    City  Salary  Experience
0   Sachin         IT  Indore   50000           2
2     Amit         IT  Indore   60000           4
3     Neha    Finance  Mumbai   55000           3
5    Karan    Finance  Mumbai   70000           6
6    Rohit         IT    Pune   65000           5
8    Ankit    Finance  Mumbai   72000           7
9   Simran         IT    Pune   62000           4

In [22]:
df

  Employee Department    City  Salary  Experience
0   Sachin         IT  Indore   50000           2
1    Rahul         HR   Delhi   40000           1
2     Amit         IT  Indore   60000           4
3     Neha    Finance  Mumbai   55000           3
4    Priya         HR   Delhi   45000           2
5    Karan    Finance  Mumbai   70000           6
6    Rohit         IT    Pune   65000           5
7    Pooja         HR   Delhi   48000           2
8    Ankit    Finance  Mumbai   72000           7
9   Simran         IT    Pune   62000           4

In [23]:
df.groupby("Department")["Salary"].agg("mean")

Department
Finance    65666.666667
HR         44333.333333
IT         59250.000000
Name: Salary, dtype: float64